name: 'Init CI'
description: 'Boostrap repo for testing'
inputs:
  node:
    default: "15.x"
    description: 'Node.js version'
    required: false
runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node }}
