#

name: "[Boto] Act if @SocialGroovyBot is called"

description: "Checks PR Comments and react to @SocialGroovyBot calls"

runs:
  using: "composite"

  steps:
    - name: Listen to PR Comments
      id: prcomm
      uses: machine-learning-apps/actions-chatops@master
      with:
        TRIGGER_PHRASE: "@SocialGroovyBot"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
