#

name: "[Boto] Act if @SocialGroovyBot is called"

description: "Checks PR Comments and react to @SocialGroovyBot calls"

runs:
  using: "composite"

  steps:
    - shell: bash
      name: Listen for PR Comments
      run: "echo actions"
