jobs:
  ci:
    name: Quality
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - uses: "dhall-lang/setup-dhall@35fa9f606036a9b7138bcbc4d519021fdda7bd5e"
        with: {}
      - run: make
      - run: git diff --color=always --exit-code
name: Dhall
on:
  push: {}
