name: Dhall freezer
on:
  push: {}
jobs:
  freezer:
    name: Freeze all .dhall files and commit changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
          branch: ${{ steps.comment.outputs.branch }}
      - uses: "./actions/dhall-freezer"
      - name: Status
        run: |
          git status
      - uses: EndBug/add-and-commit@v5
        env:
          GITHUB_TOKEN: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
        with:
          author_email: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          author_name: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          branch: ${{ steps.comment.outputs.branch }}
          message: "chore(:robot:): dhall freezering"
