name: SocialGouv Factory
on:
  pull_request:
    paths:
      - .github/workflows/socialgouv.factory.yaml
  workflow_dispatch:
jobs:
  update:
    name: Factory Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
      - uses: "./actions/factory"
      - uses: EndBug/add-and-commit@v5
        env:
          GITHUB_TOKEN: ${{ secrets.SOCIALGROOVYBOT_BOTO_PAT }}
        with:
          author_email: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          author_name: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          branch: ${{ steps.comment.outputs.branch }}
          message: "chore(:robot:): socialgouv factory update"
          add: ".github/"
